apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: default
spec:
  type: NodePort  # Exposes Prometheus on a port accessible from outside the cluster
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090  # Optional: Choose a port between 30000-32767
  selector:
    app: prometheus
