apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your-docker-username/backend-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3500
          env:
            - name: MONGO_URI
              value: mongodb://mongodb-service:27017/shoppify  # Service name for MongoDB

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3500
      targetPort: 3500
  type: ClusterIP
