apiVersion: v1
kind: Service
metadata:
  name: mongodb-service  # <--- Add this line
  labels:
    app.kubernetes.io/managed-by: Helm
    app: mongodb  # <-- Add this if you have 'app: mongodb' in your Deployment
  annotations:
    meta.helm.sh/release-name: mongodb
    meta.helm.sh/release-namespace: default

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 27017
  selector:
    app: mongodb
