apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb-service.default.svc.cluster.local:27017/shoppify"
  - name: DB_NAME
    value: "shoppify"
  - name: PORT
    value: "3500"
  - name: JWT_SECRET
    value: "your_jwt_secret"
  - name: JWT_EXPIRES_IN
    value: "1d"
  - name: FRONTEND_URL
    value: "http://your-frontend-url"

