apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/frontend
    repoURL: https://github.com/Dnahom/devops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
