image:
  repository: your-docker-username/backend-image
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: backend-service
  type: ClusterIP
  port: 3500
  
mongodb:
  host: mongodb-service.default.svc.cluster.local  # Correct format for internal communication
  port: 27017
