image:
  repository: your-docker-username/backend-image
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: backend-service
  type: ClusterIP
  port: 3500
  
mongodb:
  host: mongodb-service
  port: 27017
